### ISSUE TITLE
False negative for JCP (Ovid/WK/LWW)

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#101]
https://doi.org/10.1097/00005344-200010000-00008 is available from the publisher at https://journals.lww.com/cardiovascularpharm/Fulltext/2000/10000/Binding_Properties_of___Blockers_at_Recombinant.8.aspx , albeit with the usual annoying interstitial (Ovid vs. LWW) and only in HTML or EPUB format (the EPUB works in Calibre and Okular).

API:
```
{
  "best_oa_location": null,
  "data_standard": 2,
  "doi": "10.1097/00005344-200010000-00008",
  "doi_url": "https://doi.org/10.1097/00005344-200010000-00008",
  "genre": "journal-article",
  "is_oa": false,
  "journal_is_in_doaj": false,
  "journal_is_oa": false,
  "journal_issns": "0160-2446",
  "journal_name": "Journal of Cardiovascular Pharmacology",
  "oa_locations": [],
  "published_date": "2000-10-01",
  "publisher": "Ovid Technologies (Wolters Kluwer Health)",
  "title": "Binding Properties of \u03b2-Blockers at Recombinant \u03b21-, \u03b22-, and \u03b23-Adrenoceptors",
  "updated": "2018-06-17T07:44:02.787177",
  "year": 2000,
}
```

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/ecae926b0858021898accb190898a4edc0f9027c3ed880eaeaaa9a5bbb012227
