### ISSUE TITLE
False negative for Nature Plants paper I wrote *sad face*

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#105]
Journal version is paywalled at Nature Plants: https://doi.org/10.1038/s41477-017-0019-3

Only a grey padlock is displayed with the browser extension.

But there's a legal, AAM version at the University of Cambridge institutional repository: https://www.repository.cam.ac.uk/handle/1810/270235 

![image](https://user-images.githubusercontent.com/824120/48077851-343ae900-e1e0-11e8-95e0-78ad46985e02.png)

**Comment by hpiwowar** [comment]
Fixed!
Did a quick fix -- will look further into why it wasn't picked up and if there are further issues with the Cambridge IR, tracked separately.
