### ISSUE TITLE
False negatives for Harvard Papers in Botany

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#106]
For the journal _Harvard Papers in Botany_ Print ISSN: 1043-4534. Online ISSN: 1938-2944

The recent material from 2014 to current is available via a departmental website (not a brilliant way of doing it but 🤷‍♂️ ) https://huh.harvard.edu/pdf-downloads 

e.g.

| DOI  | Free Version |
| ------------- | ------------- |
| https://doi.org/10.3100/hpib.v19iss1.2014.n1 | https://huh.harvard.edu/files/herbaria/files/19_1_1_fox_cullen.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n2 | https://huh.harvard.edu/files/herbaria/files/19_1_23_al-shehbaz_martinez.pdf  |
| https://doi.org/10.3100/hpib.v19iss1.2014.n3 | https://huh.harvard.edu/files/herbaria/files/19_1_25_al-shehbaz.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n4 | https://huh.harvard.edu/files/herbaria/files/19_1_53_al-shehbaz_etal.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n5 | https://huh.harvard.edu/files/herbaria/files/19_1_73_meneguzzo.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n6 | https://huh.harvard.edu/files/herbaria/files/19_1_77_ormerod_i.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n7 | https://huh.harvard.edu/files/herbaria/files/19_1_97_ormerod_ii.pdf.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n8 | https://huh.harvard.edu/files/herbaria/files/19_1_117_dressler_pupulin.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n9 | https://huh.harvard.edu/files/herbaria/files/19_1_123_demoraes_etal_i.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n10 | https://huh.harvard.edu/files/herbaria/files/19_1_133_demoraes_etal_ii.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n11 | https://huh.harvard.edu/files/herbaria/files/19_1_143_demoraes_etal_iii.pdf |
| https://doi.org/10.3100/hpib.v19iss1.2014.n12 | https://huh.harvard.edu/files/herbaria/files/19_1_157_index_new_names.pdf 
| https://doi.org/10.3100/hpib.v19iss1.2014.n13 | https://huh.harvard.edu/files/herbaria/files/19_1_159_errata.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n1 | https://huh.harvard.edu/files/herbaria/files/19_2_161_al-shehbaz_german.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n2 | https://huh.harvard.edu/files/herbaria/files/19_2_175_aymard_etal.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n3 | https://huh.harvard.edu/files/herbaria/files/19_2_185_cornejo_hagsater.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n4 | https://huh.harvard.edu/files/herbaria/files/19_2_189_cornejo_etal.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n5 | https://huh.harvard.edu/files/herbaria/files/19_2_193_pupulin_bogarin.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n6 | https://huh.harvard.edu/files/herbaria/files/19_2_201_ahmad.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n7 | https://huh.harvard.edu/files/herbaria/files/19_2_203_romero_gomez.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n8 | https://huh.harvard.edu/files/herbaria/files/19_2_219_santamaria-aguilar_etal.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n9 | https://huh.harvard.edu/files/herbaria/files/19_2_227_grant_i.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n10 | https://huh.harvard.edu/files/herbaria/files/19_2_241_grant_ii.pdf |
| https://doi.org/10.3100/hpib.v19iss2.2014.n11 | https://huh.harvard.edu/files/herbaria/files/19_2_247_chang.pdf |

**Comment by hpiwowar** [comment]
thanks Ross! We'll get it fixed.

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/639b68bf78a4976803cb3b4979e27c962fe024f1c1d05953fe62bdf6d8fb0235
