### ISSUE TITLE
False negatives for Museum of Comparative Zoology - Harvard University publications

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#107]
Seven vessels worth of content is available for free from the museum website (an 'OpenScholar' Drupal based platform). The DOIs unfortunately resolve to BioOne where the content is largely paywalled.

The journals/publications are:

* Breviora http://publications.mcz.harvard.edu/index.html?publication=Breviora 
* Bulletin of the Museum of Comparative Zoology http://publications.mcz.harvard.edu/index.html?publication=bullmcz
* Bulletin of the Museum of Comparative Zoology Special Publications http://publications.mcz.harvard.edu/index.html?publication=bullmczsp 
* Memoirs of the Museum of Comparative Zoology http://publications.mcz.harvard.edu/index.html?publication=memoirs
* Occasional Papers on Mollusks http://publications.mcz.harvard.edu/index.html?publication=occpapmol 
* Special Occasional Publication [on Mollusks] http://publications.mcz.harvard.edu/index.html?publication=spoccpapmol
* Johnsonia http://publications.mcz.harvard.edu/index.html?publication=johnsonia 

Let me know if you'd like someone to do the task of linking DOIs to free PDFs for these

e.g.

Downs, J. P., E. B. Daeschler, A. M. Long and N. H. Shubin. 2018. Eusthenopteron jenkinsi sp. nov. (Sarcopterygii, Tristichopteridae) from the Upper Devonian of Nunavut, Canada, and a review of Eusthenopteron taxonomy. Breviora, 562:1-24

DOI: https://doi.org/10.3099/MCZ44.1
Free PDF: https://mczbase.mcz.harvard.edu/specimen_images/publications/Breviora_562.pdf

**Comment by hpiwowar** [comment]
Thanks Ross.  I think we can get it, assuming OpenScholar has an OAI-PMH endpoint.  Will look into it.

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/b96d2682eb3077bff3d8dff1840a0be7f13df8499e727b9db65d7a56efd29dff
