### ISSUE TITLE
Open access article in hybrid journal marked as closed

### ISSUE THREAD

**Issue by peterdesmet** [Impactstory/oadoi#11]
This article: http://doi.org/10.1007/s10344-012-0655-x is marked as "Open access" in the hybrid Springer journal "European Journal of Wildlife Research". The PDF can be found here: http://link.springer.com/content/pdf/10.1007%2Fs10344-012-0655-x.pdf

According to oadoi it is "closed": https://api.oadoi.org/v1/publication/doi/10.1007/s10344-012-0655-x rather than "hybrid journal" and does not provide a `free_fulltext_url`.

Any ideas why?

**Comment by eocarragain** [comment]
+1

The OADOI api still gives the wrong response for this. Doai/dissime.in identifies the Gold version as well as two researchgate versions: http://dissem.in/api/10.1007/s10344-012-0655-x

**Comment by eocarragain** [comment]
@peterdesmet @hpiwowar fixed in v2 api: https://api.oadoi.org/v2/publication/doi/10.1007/s10344-012-0655-x

**Comment by jasonpriem** [comment]
thanks very much for following up on this @eocarragain !
