### ISSUE TITLE
False negatives for Acta Geologica Sinica (English Edition)

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#113]
The DOIs resolve to Wiley's platform, where the content is paywalled. However, over at the website of the Geological Society of China, whose journal this actually is (i.e. this is legally provided access), much of the recent content is freely accessible.

e.g. 

| DOI  | Free Version |
| ------------- | ------------- |
| https://doi.org/10.1111/1755-6724.13480 | http://www.geojournals.cn/dzxbcn/ch/reader/create_pdf.aspx?file_no=2017endzxb06040&flag=1&journal_id=dzxbcn&year_id=2017 |
| https://doi.org/10.1111/1755-6724.13445 | http://www.geojournals.cn/dzxbcn/ch/reader/create_pdf.aspx?file_no=2017endzxb06003&flag=1&journal_id=dzxbcn&year_id=2017 |

landing page link rather than direct-to-PDF link for the later one is here: http://www.geojournals.cn/dzxbcn/ch/reader/view_abstract.aspx?file_no=2017endzxb06003&flag=1

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/32057de6088fe627f3ee4b997c041b623fdd9d3da149dd3eebb0d3c00cff8507
