### ISSUE TITLE
False negatives found via new 'reverse flipped' journals article

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#114]
I was reading 'Matthias, L.; Jahn, N.; Laakso, M. The Two-Way Street of Open Access Journal Publishing: Flip It and Reverse It. Publications 2019, 7, 23. https://doi.org/10.3390/publications7020023'

and have seen that for some of the journals that have reverse flipped, the 'new' publisher has additionally paywalled all the old content that was made OA at the previous publisher/platform e.g. Redalyc or Scielo.

An example is the journal _Actas Urológicas Españolas_

Content is solely behind a paywall at Elsevier from 2012 onwards.
However content is OA at Scielo from 2003 to 2011.
Elsevier also make the 2003 to 2011 content available behind a paywall and it is where the DOI resolves to(!).

e.g. Vol35 issue 10 paywalled here: https://www.sciencedirect.com/journal/actas-urologicas-espanolas/vol/35/issue/10
Vol35 issue 10 open access here: http://scielo.isciii.es/scielo.php?script=sci_issuetoc&pid=0210-480620110010&lng=es&nrm=iso 

Hundreds of articles to link-up. There may be many more such in the 152 journals identified by Matthias et al

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/26c380d0d1addbf6d9e032d04adc3ca596fa2f0fdbdb3bf609a23214886ba529
