### ISSUE TITLE
Wrong CC license inferred on post at The Winnower

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#115]
As seen via lens.org

https://www.lens.org/lens/scholar/article/027-328-274-276-223/main 

My blog post at the Winnower (http://dx.doi.org/10.15200/winn.142421.13440) contains a mention of " the CC-BY-NC-ND licence " within the body text. But actually the work itself is licensed under CC BY.

😄

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/a5b007887b9712211988edb7edb6592e2d87e37496e3025d0cabe4e4012cf068
