### ISSUE TITLE
False negative for USDA NALDC

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#116]
The National Agricultural Library Digital Collections of the United States Department of Agriculture discontinued all (?!) the previous naldc.nal.usda.gov URLs, which now go nowhere (to the main page). They need to be rewritten into naldc-**legacy**.nal.usda.gov, at least until the old content is migrated to the new website.

https://oadoi.org/10.1016/j.chroma.2005.05.009 used to redirect to https://naldc.nal.usda.gov/naldc/download.xhtml?id=37397&content=PDF, and now redirects to the publisher URL.

However, the same content is still available at https://naldc-legacy.nal.usda.gov/naldc/download.xhtml?id=37397&content=PDF . I don't know if the same discovery mechanism formerly used to find this URL (OAI-PMH?) is available with the new domain as well. http://v2.sherpa.ac.uk/id/repository/1014 is silent about it.

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/ae8dd7893a809bc1293a196332da06ab64a0ffc0e14a773c5b9825856c452cc9
