### ISSUE TITLE
False negative from NBER

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#117]
https://oadoi.org/10.1093/qje/qjy005 redirects to the closed-access publisher location, but several preprint and postprint versions are available elsewhere.

The "easiest" to find is probably https://www.nber.org/papers/w21331, which includes a link to https://www.nber.org/papers/w21331.pdf and to the published version.

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/58345d7bd47d699cc45ff7c9b13ae4ed58fe0516758ab6830a0993d0baee60fc
