### ISSUE TITLE
False negative for chemRxiv

### ISSUE THREAD

**Issue by fxcoudert** [Impactstory/oadoi#118]
This paper https://pubs.acs.org/doi/10.1021/acs.langmuir.8b01115 is available from chemRxiv https://chemrxiv.org/articles/Structure_and_Dynamics_of_Water_Confined_in_Imogolite_Nanotubes/6287810 but it is not picked up.

**Comment by fxcoudert** [comment]
Actually there seem to be several others: https://www.nature.com/articles/s41563-019-0317-4 is not picked up from https://chemrxiv.org/articles/Pressure_Promoted_Low-Temperature_Melting_of_Metal-Organic_Frameworks/6541190/3

**Comment by fxcoudert** [comment]
Another example: https://doi.org/10.1016/j.ccr.2019.02.023 and https://chemrxiv.org/articles/Meta-MOFs_Framework_Materials_with_Anomalous_Behavior/7415249

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/b86b0188470d9ba70667a3fa64e226c92d56d7388e4b3774a2666f2bd7564a6f
