### ISSUE TITLE
API is not recognising valid DOI

### ISSUE THREAD

**Issue by fxcoudert** [Impactstory/oadoi#119]
When the API is asked for information about DOI `10.1038/s41557-019-0236-7`, by loading https://api.unpaywall.org/v2/10.1038/s41557-019-0236-7?email=XXX it says:

```
{
    "HTTP_status_code": 404, 
    "error": true, 
    "message": "'10.1038/s41557-019-0236-7' is an invalid doi.  See http://doi.org/10.1038/s41557-019-0236-7"
}
```

But that's not true, the DOI is valid and http://doi.org/10.1038/s41557-019-0236-7 actually resolves without issue.

**Comment by richard-orr** [comment]
This is a valid DOI for which we hadn't retrieved metadata yet.
