### ISSUE TITLE
Best way to integrate as python module?

### ISSUE THREAD

**Issue by gg4u** [Impactstory/oadoi#12]
Hello,

I am working on a web app to help spread out science!
Just found oaDOI - Amazing.
My app is in flask, too. How wonder which is the best way to integrate oaDOI - using requests, or is there a oaDOI python modul too ? (something like for wikipedia..)

Thank you!

**Comment by michaelavoigt** [comment]
any news on this? python module for oaDOI would be great!

**Comment by hpiwowar** [comment]
calling the api using requests is the best way.  there is no python module.

best,
Heather


--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by michaelavoigt** [comment]
Thanks @hpiwowar for the immediate reply. Maybe the issue could be closed then?

Just for future reference and those that try to find a way to call the oaDOI API without scripting on their own – check out this awesome manual: 
[John Holmberg Runsten: Collecting-Open-Access-information-using-OpenRefine-and-the-oaDOI-API](http://www.libraryworkflowexchange.org/wp-content/uploads/2017/07/Collecting-Open-Access-information-using-OpenRefine-and-the-oaDOI-API.pdf)

This tutorial explains how OpenRefine (http://openrefine.org/) together with the oaDOI API (https://oadoi.org/) from Impactstory can be used to collect Open Access information. aoDOI collects open access evidence from DOAJ, crossref, BASE, and pmicd. This can be useful when trying to identify OA articles published by one’s institution. In this tutorial records from Scopus have been used.
[via libraryworkflowexchange.org](http://www.libraryworkflowexchange.org/2017/07/06/collecting-open-access-information-using-openrefine-and-the-oadoi-api)

**Comment by hpiwowar** [comment]
That's really cool!  Thanks for posting the link :)
