### ISSUE TITLE
False negative from arXiv

### ISSUE THREAD

**Issue by fxcoudert** [Impactstory/oadoi#120]
This paper https://pubs.acs.org/doi/10.1021/ja805129c is available from arXiv at https://arxiv.org/abs/1904.09588 where its DOI is included.

**Comment by fxcoudert** [comment]
Same is true of https://aip.scitation.org/doi/10.1063/1.2964101 which is available on arXiv at https://arxiv.org/abs/1211.0669 (and where the DOI is filled)

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/b60a5c203e463175e370bc3a513002539f71f8d398e371c980618a79a40df14c
