### ISSUE TITLE
Update DOAJ info via API or daily dump

### ISSUE THREAD

**Issue by njahn82** [Impactstory/oadoi#14]
Great tool!  

It seems like the DOAJ journal info is outdated:

https://github.com/Impactstory/oadoi/blob/ce1e51109151674e9a6c69b448cebacc9c19eb1e/oa_local.py#L167

Instead of using a data dump,  why not implement either the API <https://doaj.org/api/v1/docs> or download the csv on a daily basis?

**Comment by hpiwowar** [comment]
Hi!  To help us prioritize -- have you run into trouble with bad results due to an outdated DOAJ entry?  I know it can happen, but am interested in knowing how much it actually does, so we can balance with other dev needs.   Thanks :)

**Comment by njahn82** [comment]
Hi! It is not a big issue, and not a technical one. Guess, I should have
rather used your contact form.

I just wondered why recently published articles in the Journal of High
Energy Physics, an open access journal, were marked as "closed". The
journal has been listed in the DOAJ since 7 December 2016.

Maybe it helps, when you just make the date when you obtained the data
dumps you are using available in the docu to avoid confusion

**Comment by hpiwowar** [comment]
Cool.  No problem at all, it's useful to hear.  Good thought on the dump date too.  Thanks Najko!

**Comment by ioverka** [comment]
Is oaDOI still using data dumps from DOAJ? Here is an example for a "false positive" associated to a journal listed in DOAJ: http://api.oadoi.org/10.1051/epjconf/201714302020

Corresponding journal/series record in DOAJ: https://doaj.org/toc/2100-014X
