### ISSUE TITLE
False positive found in BASE

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#16]
API request: https://api.oadoi.org/10.1063/1.3498143?email=test@example.com

```
      "evidence": "oa repository (via BASE title and first author match)", 
      "free_fulltext_url": "http://hdl.handle.net/11858/00-001M-0000-0011-F762-1", 
      "is_boai_license": false, 
      "is_free_to_read": true,
```

Unfortunately, MPG.Pure at this point does not provide a free available full text for this article and the corresponding BASE record isn't tagged as Open Access as well, see https://www.base-search.net/Record/80f7021d709ff90c2c2cd0ef2185f2d03f6c660344f7345221b4bd1926ae105e/

**Comment by eocarragain** [comment]
This appears to now be fixed (i.e. it no longer links to MPG and gives a status of "closed") in the current API response: https://api.oadoi.org/10.1063/1.3498143?email=test@example.com

The item is available through researchgate as caught by doai/dissem.in (and presumably unpaywall through google scholar): http://dissem.in/api/10.1063/1.3498143

suggest closing this issue

**Comment by eocarragain** [comment]
@hpiwowar @ioverka also correct in v2 api: https://api.unpaywall.org/v2/10.1063/1.3498143

**Comment by ioverka** [comment]
Thank you, @eocarragain
