### ISSUE TITLE
Open Access available through doai.io but not available through oadoi

### ISSUE THREAD

**Issue by moqri** [Impactstory/oadoi#19]
doai.io:
http://doai.io/10.1287/isre.2015.0618

oadoi:
https://api.oadoi.org/10.1287/isre.2015.0618

**Comment by nemobis** [comment]
DOAI redirects to ResearchGate, which oaDOI doesn't want to do AFAIK.

**Comment by eocarragain** [comment]
The unpaywall plugin will redirect to ResearchGate as it dynamically queries Google Scholar (which indexes ResearchGate) in addition to relying on oadoi. The oadoi API itself doesn't have this functionality.

**Comment by hpiwowar** [comment]
That's true!  Thanks everybody for answering :)
