### ISSUE TITLE
Bug with the Proceedings of the London Mathematical Society

### ISSUE THREAD

**Issue by wetneb** [Impactstory/oadoi#2]
Any idea what happens to this DOI: http://api.oadoi.org/v1/publication/doi/10.1112/plms/s2-43.6.544
The free link is broken…
(In case you wonder, Dissemin also gets it wrong ^^)

**Comment by zuphilip** [comment]
It seems that this information comes from base: https://www.base-search.net/Search/Results?lookfor=10.1112%2Fplms%2Fs2-43.6.544&type=all&oaboost=1&ling=1&name=&newsearch=1&refid=dcbasde . And base claims to have this info from the Stanford University...

**Comment by wetneb** [comment]
Yeah… it seems like we would need oaDOI's scraping even on pages classified as OA by BASE?

**Comment by eocarragain** [comment]
+1 to scraping pages that Base suggests are OA. I've come across quite a few examples where oadoi links to an institutional repository page but the item is actually under embargo. Scraping the splash-page to confirm pdf availability would help.
