### ISSUE TITLE
"found_hybrid" is false for OA content on Hogrefe platform

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#22]
request: https://api.oadoi.org/10.1027/1864-9335/a000178?email=test@example.com

full text is tagged as "Open Access" on publisher platform: http://econtent.hogrefe.com/doi/full/10.1027/1864-9335/a000178

summer greetings from Munich,
inga ;)

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/cc2a641d805858b0ffc2f8006fddcd12dea9e57a2aae51c0a4ab16792dce2813
