### ISSUE TITLE
free access not detected for a significant portion of outputs at CUP journal Oryx

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/oadoi#23]
I'm trying to do a journal-level analysis of recent content, say post-2010 to investigate levels of open access: identifying both gold and green for Oryx (CUP).

The trouble is there is a significant portion (>50% for some issues!) of Oryx content that is _incorrectly_ assessed by oadoi as "closed" when they are in fact free (blue) access, e.g.

https://doi.org/10.1017/S0030605313001300
https://doi.org/10.1017/S0030605313001439
https://doi.org/10.1017/S0030605313001440
https://doi.org/10.1017/S0030605314000143
https://doi.org/10.1017/S003060531300152X
https://doi.org/10.1017/S0030605313001531
https://doi.org/10.1017/S0030605314000052
https://doi.org/10.1017/S0030605314000386
https://doi.org/10.1017/S0030605314000301

If one looks at the issue page of journal, typically this incorrectly assessed material lies within the "Editorial",  "Conservation news"  or "Briefly" sections.

**Comment by nemobis** [comment]
I see there is quite a bit of metadata in the HTML meta tags, but do you have an OAI-PMH endpoint? I cannot find any on https://www.base-search.net/about/en/about_sources_date.php?menu=2&submenu=1 and there is no mention of OAI-PMH in your website; the latest information I find on the topic is http://liblicense.crl.edu/ListArchives/0603/msg00034.html according to which in 2006 Cambridge Journals Online supported OAI-PMH, but https://www.cambridge.org/core/services/librarians/cambridge-core-url-mapping says CJO is no longer accessible and makes no mention of feature parity, so there might have been a regression.

**Comment by richard-orr** [comment]
f81917bbbe500017300e1194558530c3e0edcdaf
