### ISSUE TITLE
false positive for journal Synthesis [0039-7881, 1437-210X] (Thieme)

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#24]
example: http://api.oadoi.org/10.1055/s-0032-1316757 

```
      "evidence": "oa journal (via journal title in doaj)",
      [...]
      "free_fulltext_url": "http://doi.org/10.1055/s-0032-1316757",

```

Full text is protected by a paywall by the publisher, the journal "Synthesis" cannot be found in DOAJ, see: https://doaj.org/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22journal%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22synthesis%22%2C%22default_field%22%3A%22bibjson.title%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Could you have a look at this? Thanks,
inga

**Comment by ioverka** [comment]
Here some more examples for which oaDOI reports that a free available full text is available on the publisher platform, but it's not:

https://api.oadoi.org/10.1055/s-0036-1588699
https://api.oadoi.org/10.1055/s-0036-1589482
https://api.oadoi.org/10.1055/s-0035-1560509
https://api.oadoi.org/10.1055/s-0036-1588868
https://api.oadoi.org/10.1055/s-0032-1318154
https://api.oadoi.org/10.1055/s-0036-1588913
https://api.oadoi.org/10.1055/s-0036-1588371
https://api.oadoi.org/10.1055/s-0036-1588838
https://api.oadoi.org/10.1055/s-0034-1379965
https://api.oadoi.org/10.1055/s-0032-1317697
https://api.oadoi.org/10.1055/s-0034-1380414
https://api.oadoi.org/10.1055/s-0033-1338501
https://api.oadoi.org/10.1055/s-0034-1379942
https://api.oadoi.org/10.1055/s-0031-1289765
https://api.oadoi.org/10.1055/s-0036-1588607
https://api.oadoi.org/10.1055/s-0036-1588405
https://api.oadoi.org/10.1055/s-0034-1380405

Any chance for an update?

**Comment by hpiwowar** [comment]
thanks for the examples!  Yup, we'll be fixing these soon by looking them up by issn rather than title.  will close this issue when it goes live.

**Comment by hpiwowar** [comment]
fixed!
