### ISSUE TITLE
False negatives for various HAL

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#26]
Several of the articles in https://dissem.in/search/?authors=martin+monperrus&status=couldbe are false negatives both for DOAI and oaDOI even if they are available in some HAL.

For instance http://oadoi.org/10.1109/ICSE-NIER.2017.8 goes to IEEE even if it's available in HAL and arXiv: BASE knows 7 records for this title, including https://www.base-search.net/Record/ee270fcd08a12d9f0570d4e82f142724369a9243a495cc5db9431209a79fbe42/ for https://arxiv.org/abs/1609.06848, which however doesn't have the DOI.

https://hal.inria.fr/hal-01346046 is known to https://www.base-search.net/Record/8ccbbc42d4fb097112f68b2002d2f4fb6c6037bd509ec3271aa244eb8b5b23a4/ but oaDOI goes to https://link.springer.com/article/10.1007%2Fs11219-016-9332-8 .

**Comment by monperrus** [comment]
Some Base records are not considered as open-access even if there is a PDF url, such as [the one you mention](https://www.base-search.net/Record/8ccbbc42d4fb097112f68b2002d2f4fb6c6037bd509ec3271aa244eb8b5b23a4/)

There is an inter-operability problem between HAL and BASE see https://github.com/CCSDForge/HAL/issues/8

**Comment by monperrus** [comment]
can be closed, the discussion continues on #53
