### ISSUE TITLE
False negative for a Wiley CNE editorial

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#28]
https://doi.org/10.1002/cne.24058 is marked as closed access at http://api.oadoi.org/10.1002/cne.24058 , but in fact all its content is available at http://onlinelibrary.wiley.com/doi/10.1002/cne.24058/full (perhaps because it's an editorial). This can seemingly be noticed by the lack of a link to a for-pay PDF in the HTML and by the presence of a link to the PDF http://onlinelibrary.wiley.com/doi/10.1002/cne.24058/epdf in JavaScript, or by the link to a PDF http://onlinelibrary.wiley.com/doi/10.1002/cne.24058/pdf in the "old article view" http://onlinelibrary.wiley.com/wol1/doi/10.1002/cne.24058/full .

The article is not indexed by BASE, although one of its sources is "Wiley Online Library (Open Access Articles via Crossref)" https://www.base-search.net/Search/Results?q=dccoll:crwiley&refid=dctableen

**Comment by nemobis** [comment]
BASE informed me that they can do little about the Wiley OAI-PMH, which has only some 8000 records registered as OA even though the total amount of records is around one million.

Another example: http://onlinelibrary.wiley.com/doi/10.1111/tsq.12115/full

**Comment by eocarragain** [comment]
@hpiwowar @nemobis fixed in v2 api: http://api.oadoi.org/v2/10.1002/cne.24058

**Comment by jasonpriem** [comment]
thanks @eocarragain 🙏
