### ISSUE TITLE
Missing philpapers.org URLs

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#30]
Several philpapers.org copies are missing from the API although they are indexed in BASE. For instance:
* http://api.oadoi.org/10.1007/s10670-007-9081-y has https://www.escholar.manchester.ac.uk/api/datastream?publicationPid=uk-ac-man-scw:1b5581&datastreamId=PRE-PEER-REVIEW.PDF but not https://philpapers.org/rec/LIGQPA
* http://api.oadoi.org/10.5840/monist201497430 has citeseerx and OUPjournals (as in from https://www.base-search.net/Record/f7597f7a4718f297bf7fbb8494f6fb3724d57b0713f8ec9fcd22d5d55d714122/ ) but not https://www.pdcnet.org/monist/content/monist_2014_0097_0004_0460_0478 nor https://www.research.manchester.ac.uk/portal/files/27815946/POST-PEER-REVIEW-PUBLISHERS.PDF (linked indirectly by https://www.base-search.net/Record/bac4a8a5d97770fd51e2924993c2ce0763211d4dbae4794975fd3562de6a1eff/ , perhaps because it has two PDFs )
* http://api.oadoi.org/10.1093/bjps/axt012 has http://philpapers.org/archive/LIGAEA.pdf but gives precedence to http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.482.4067

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/f309753d9770913fb6eaabf41dbde99d01eaae9cfd40e4bb943a064ee00220ff
