### ISSUE TITLE
False negative for Thieme Synthesis article

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#31]
https://www.thieme-connect.de/products/ejournals/html/10.1055/s-2007-965924 is open access but http://api.oadoi.org/10.1055/s-2007-965924 says it's closed. To be reported to CrossRef? Thieme is not in BASE yet and I couldn't find an OAI-PMH endpoint, I wrote them.

**Comment by ioverka** [comment]
Are you sure that this full text is available for free? I'm redirected to <https://profile.thieme.de/HTML/sso/ejournals/login.htm?type=default&subsidiary=www.thieme-connect.de&hook_url=https%3A%2F%2Fwww.thieme-connect.de%2Fproducts%2Fejournals%2Fhtml%2F10.1055%2Fs-2007-965924> where Thieme asks me to login, see:

![thieme-access](https://user-images.githubusercontent.com/8920469/30066635-c2173cfc-9258-11e7-9170-dfb737ceb7c9.png)

Alternatively, maybe request Thieme to report [license information to CrossRef](https://github.com/CrossRef/rest-api-doc/blob/master/funder_kpi_metadata_best_practice.md#license-information)? That might be easier than setting up a OAI PMH data provider... and BASE reads information from CrossRef as well.

See also: #24

**Comment by nemobis** [comment]
No, I'm not sure the full text is available: I'm redirected to a login page too now. I was at home when I reported this so I'm not sure what happened. I could close this, your issue seems to have better info.

Yes, BASE and CrossRef would be happy to receive such information (cf. https://github.com/Impactstory/oadoi/issues/28 ), but I'm not sure what's an effective way to ask. I've written some journals and asked some authors to ask their journals, but I didn't get replies so far. If you work for a Thieme customer then maybe you could try and contact them.

**Comment by ioverka** [comment]
I'm not representing a customer, but we have some contacts at Thieme... I'll give it a try. They get a place on my growing list of publishers to bug from time to time as well ;)

**Comment by hpiwowar** [comment]
oaDOI now showing closed, as it should.
