### ISSUE TITLE
False negative for orbi.ulg.ac.be post-print

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#32]
http://oadoi.org/10.1093/eurheartj/ehw272 redirects to https://academic.oup.com/eurheartj/article-abstract/37/39/2999/2414995/2016-ESC-EAS-Guidelines-for-the-Management-of (paywalled) and http://api.oadoi.org/10.1093/eurheartj/ehw272 says no OA found, but a post-print is available at http://orbi.ulg.ac.be/handle/2268/205760 (correctly: http://www.sherpa.ac.uk/romeo/search.php?issn=0195-668X ), indexed at https://www.base-search.net/Record/12634e5c8fda4ba473385eda76a116e75d7212bf9297ff88d4c33ba5b7059d39/ ; probably it was missed because there are several other non-OA records from other institutional repositories https://www.base-search.net/Search/Results?lookfor=2016+ESC%2FEAS+Guidelines+for+the+Management+of+Dyslipidaemias&type=all&oaboost=1&ling=1&name=&thes=&refid=dcresen&newsearch=1

**Comment by eocarragain** [comment]
@hpiwowar @nemobis fixed in v2 api: http://api.oadoi.org/v2/10.1093/eurheartj/ehw272

**Comment by nemobis** [comment]
Looks good indeed in v2, and it seems several links were added in result on the English Wikipedia: https://en.wikipedia.org/w/index.php?search=insource%3Aorbi.ulg.ac.be
