### ISSUE TITLE
False negative for PubMed Central

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#35]
http://api.oadoi.org/10.1126/scitranslmed.aaj1921 says closed but a copy is available at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5384717/ (with the same DOI).

**Comment by eocarragain** [comment]
@hpiwowar @nemobis this is fixed in v2 api: http://api.oadoi.org/v2/10.1126/scitranslmed.aaj1921

**Comment by nemobis** [comment]
Indeed, and OAbot keeps finding new PMC IDs from older works, for instance [910 additions on the English Wikipedia](https://en.wikipedia.org/w/index.php?title=Special:Contributions/OAbot&dir=prev&offset=20180802092308&limit=910&target=OAbot) this month, which I believe were not found just few months ago.
