### ISSUE TITLE
False negative for Microbiology society

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#36]
http://api.oadoi.org/10.1099/ijsem.0.000511 says closed, but the journal provides an open PDF at http://ijs.microbiologyresearch.org/content/journal/ijsem/10.1099/ijsem.0.000511

For another paper in the same journal http://api.oadoi.org/10.1099/ijsem.0.000932 correctly reports that the PDF is available for free at http://ijs.microbiologyresearch.org/content/journal/ijsem/10.1099/ijsem.0.000932

**Comment by eocarragain** [comment]
This is data-standard for the one that doesn't work is version 1, whereas it's version 2 for the one that does work. So this can probably be closed?

**Comment by nemobis** [comment]
Yes, given http://api.oadoi.org/10.1099/ijsem.0.000932 I suppose the other DOI will work too once it's updated. (It's still good for me to have these cases tracked to avoid wondering again next time I find the same "error". I hope it's the same for you.)

**Comment by eocarragain** [comment]
Definitely - very useful to have these as reference!

**Comment by nemobis** [comment]
Reopening because the above example is ok on the API now, but 10.1099/ijsem.0.001212 isn't although it's available from the publisher: http://ijs.microbiologyresearch.org/content/journal/ijsem/10.1099/ijsem.0.001212 links http://ijs.microbiologyresearch.org/deliver/fulltext/ijsem/66/9/3443_ijsem001212.pdf?itemId=/content/journal/ijsem/10.1099/ijsem.0.001212&mimeType=pdf&isFastTrackArticle=

```
{
  "best_oa_location": null,
  "data_standard": 2,
  "doi": "10.1099/ijsem.0.001212",
  "doi_url": "https://doi.org/10.1099/ijsem.0.001212",
  "genre": "journal-article",
  "is_oa": false,
  "journal_is_in_doaj": false,
  "journal_is_oa": false,
  "journal_issns": "1466-5026,1466-5034",
  "journal_name": "International Journal of Systematic and Evolutionary Microbiology",
  "oa_locations": [],
  "published_date": "2016-09-01",
  "publisher": "Microbiology Society",
  "title": "Pseudogracilibacillus marinus sp. nov., isolated from a biofilm formed in coastal seawater",
  "updated": "2018-06-21T15:02:25.370435",
  "year": 2016,
  "z_authors": null
}
```
