### ISSUE TITLE
DOI status report - keep field "doi_resolver"?

### ISSUE THREAD

**Issue by michaelavoigt** [Impactstory/oadoi#37]
In [v1 API version](https://oadoi.org/api/v1) there is a key `doi_resolver` ("The organization in charge of issuing and resolving this DOI."). From this key you could deduct whether the DOI is corrupt (either misspelled or not properly registered).
In [v2 API version](https://oadoi.org/api/v2) you introduced 5 keys (`publisher`, `title`,` journal_issns`, `journal_name`, `year`) which (assumingly) integrates metadata from DOI registries. Information for Crossref DOIs is verbose whereas there seems to be no metadata for DataCite (cf. [example 1](https://api.oadoi.org/v2/10.5675/hywa_2013,6_2), [2](https://api.oadoi.org/v2/10.3205/zma001029) or [3](https://api.oadoi.org/v2/10.3205/000255). When all keys are `null` one can not be sure if the DOI itself is possibly incorrect.

I am aware that one can get this information from https://www.doi.org/ - but this would mean an extra step. Any chance that you re-integrate this key `doi_resolver` sinde I assume you have this infomormation anyway?
Or did I miss something - is there another way to deduct from the v2 API when there is a technical problem with the requested DOI? In that case - thanks for any advice...

**Comment by hpiwowar** [comment]
Hi!  Thanks for asking.  We now return a 404 if we have a technical problem with the DOI.  See http://api.oadoi.org/v2/10.99/9999

Hope that helps!
Best, 
Heather
