### ISSUE TITLE
Investigate using the ISSN-GOLD-OA list for identification of Gold OA journals

### ISSUE THREAD

**Issue by eocarragain** [Impactstory/oadoi#38]
Available here: http://doi.org/10.4119/unibi/2913654

The list seeks to provide a more complete overview than provided by DOAJ alone:

> ISSN-GOLD-OA 2.0 provides a matching list of ISSN for Gold Open Access (OA) journals. The intention was to compile a matching table that is as complete as possible by using different publicly available sources. The data set offers a basis for various journal-related issues in bibliometric studies on Gold OA. The list is an updated version of ISSN-GOLD-OA . For a detailed description of the method, data sources used and the definition of the table fields, please refer to the original documentation: https://pub.uni-bielefeld.de/data/2906347

Some of their findings re DOAJ coverage:

> Each ISSN and journal can be covered in one or more of the OA-sources. Numbers were
calculated after manual data cleaning. Only ~39% of all ISSNs and ~41% of all journals
are covered in DOAJ. If restricted to the ISSNs that appear in Web of Science, DOAJ
covers ~62% (Scopus: ~61%). In terms of journals: 67% in the Web of Science and 65% in
Scopus. Thus, a substantial loss of information is supposed to affect bibliometric studies
which solely rely on DOAJ.

**Comment by jasonpriem** [comment]
Very interesting! Yeah we'll look into this!

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/50c413d868ec735374e0076369b2e53d3d7a1a85324c6f2372b2e5b4e998189d
