### ISSUE TITLE
[when OA version not available] send a request using the OpenAccessButton

### ISSUE THREAD

**Issue by jibe-b** [Impactstory/oadoi#40]
Here is a suggestion (maybe have you already considered it?)

Whenever the resolving of a DOI to an OpenAccess version of a publication, a request could be made using the OpenAccessButton.

The request would then be made in the name of ImpactStory or someone in your team.

I wrote a few words about it here: https://github.com/OAButton/discussion/issues/915

As it will be the OpenAccessWeek soon www.openaccessweek.org/ it may be an acceptable moment for authors to receive such requests. And after this one week period, the test can be evaluated.

The OAB has a batch upload mode, so requests could be made with the non resolved DOIs of the day.

I'm available to help make this happen.

**Comment by jibe-b** [comment]
I continue with a suggestion to involve organizations to send requests to authors using the OpenAccessButton in their own names at https://github.com/OAButton/discussion/issues/916

As a major OA DOI resolving service, may I ask you your opinion on this? You may have a clear vision of the domain, that may help to model the process I propose in a pragmatic way.

**Comment by wetneb** [comment]
@jibe-b this repository is for oadoi (the API), I think your request should rather be for Unpaywall (the extension)

**Comment by jasonpriem** [comment]
Thanks for the suggestion! Agreed with @wetneb that it is out of scope for oaDOI, but we are interested in setting up this feature for Unpaywall, and in fact it's on the roadmap...but may not make it in in time for OA week.
