### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by wetneb** [Impactstory/oadoi#42]
Hi!

This returns a 500 error:
https://api.oadoi.org/v2/:10.1038/nature21377?email=contact@dissem.in

Cheers,
Antonin

**Comment by hpiwowar** [comment]
Sorry about that!  Working now.
Also, no need for a ":" after the /v2/ and there is a chance it may confuse
it in the future.

Cheers,
Heather


--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>
