### ISSUE TITLE
[suggestion] duplicate greenOA to archive.org

### ISSUE THREAD

**Issue by jibe-b** [Impactstory/oadoi#43]
This issue goes beyond OADOI but may make use of it.

Some self-hosted documents are no longer available on the web. I realized this while using the oabot.org, which suggested several dead links, which means some of the doai and possibly oadoi links are dead.

1. Copyright compliance: whenever a self-hosted document is clearly under a creative commons licence, it is allowed to host it somewhere else.

2. Let's write a bot that checks the license and saves green OpenAccess publications to archive.org

3. When a link is dead, it should be added to the oadoi database to indicate that the archive.org link should be used instead.

**Comment by jibe-b** [comment]
Requires:

- a bot (easy)
- an increase in number of papers with license metadata filled

**Comment by wetneb** [comment]
That's roughly what CiteSeerX is doing (without the license check). So it might be worth coordinating with them if you want to work on that.

**Comment by nemobis** [comment]
Cf. http://archiveteam.org/index.php?title=PDF_2016 if you need a few millions URLs. :)

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/9718ac0b124066b1765fad0ba301a6cb69e1bcff0ae66d2f6d62b64151d350af
