### ISSUE TITLE
False negative for University of Stirling

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#44]
http://dspace.stir.ac.uk/handle/1893/22039 is not detected at http://api.oadoi.org/v2/10.1111/1467-856X.12057 although it's in https://www.base-search.net/Record/fa44a34e280af486bce6688006e6e8486c6a9caccb5372ab798ee4e8b39c114a/ and has

```
<meta name="citation_pdf_url" content="http://dspace.stir.ac.uk/bitstream/1893/22039/1/BJPIR%20FINAL%206th%20June%202014.pdf" />
```

**Comment by ioverka** [comment]
It looks like the the dspace record is now found by oadoi/unpaywall, see the second "oa_location" in https://api.unpaywall.org/v2/10.1111/1467-856X.12057.

Would you like to close the issue, @nemobis?

**Comment by jasonpriem** [comment]
thanks very much for following up on this issue @ioverka!
