### ISSUE TITLE
suggestion: include license URL for RSC articles

### ISSUE THREAD

**Issue by michaelavoigt** [Impactstory/oadoi#46]
**Observation** for RSC articles:
* publisher includes CC license info in their Crossref metadata - but instead of the canonical tag "license" they include it in a tag "assertion" 
* publisher includes RDFa tags on the article pages to expose the CC license URL (though not as META dc.rights in HTML header) 

**Suggestion**: retrieve license URL from either Crossref metadata or from RDFa element on article page - and include license URL in oaDOI output

* Example 1
  * [RSC article page](https://dx.doi.org/10.1039/c6ob02271e) -> check HTML source...
  * [Crossref metadata](http://api.crossref.org/works/10.1039/c6ob02271e) -> check tag "assertion"
  * [oaDOI result](http://api.oadoi.org/v2/10.1039/c6ob02271e) ->  result for best_oa_location -> "license": "implied-oa"
* Example 2
  * [RSC article page](https://dx.doi.org/10.1039/c4ce01025f) -> check HTML source...
  * [Crossref metadata](http://api.crossref.org/works/10.1039/c4ce01025f) -> check tag "assertion"
  * [oaDOI result](http://api.oadoi.org/v2/10.1039/c4ce01025f) ->  result for best_oa_location -> "license": "implied-oa"

(FYI @ebunge)

**Comment by ioverka** [comment]
fyi: We contacted RSC some months ago and asked them to move the license information from assertion to license_ref. According to my understanding RSC is working on that.
