### ISSUE TITLE
Using CrossRef to check for OA preprints of requested article?

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#47]
oaDOI request: https://api.oadoi.org/v2/10.1016/j.ydbio.2017.03.003 does not return an OA version.

According to Crossref it has a preprint (element has-preprint in http://api.crossref.org/works/10.1016/j.ydbio.2017.03.003) and that would be free to read, see https://doi.org/10.1101/041632.

**Comment by eocarragain** [comment]
+1 very useful

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/f2daf0f06bd1ff59967bbfbbc1dcfe48f4eee76e699043b47a0329fdd0fa56e4
