### ISSUE TITLE
False negative for Annals of Emergency Medicine

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#48]
http://api.oadoi.org/v2/10.1016/S0196-0644(95)70322-5 says not OA but http://www.annemergmed.com/article/S0196-0644(95)70322-5/pdf is available.

**Comment by eocarragain** [comment]
@nemobis @jasonpriem i can't access the PDF on annemergmed.com

**Comment by nemobis** [comment]
> @nemobis @jasonpriem i can't access the PDF on annemergmed.com

I can't either, even after enabling cookies. My mistake, or something weird.
