### ISSUE TITLE
New oa licenses

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#49]
There are some additional OA licenses in Crossref records, see 

http://api.crossref.org/works?filter=license.url:http://www.ieee.org/publications_standards/publications/rights/oapa.pdf

http://api.crossref.org/works?filter=license.url:http://aspb.org/publications/aspb-journals/open-articles

http://api.crossref.org/works?filter=license.url:https://doi.org/10.1364/OA_License_v1

It looks like oaDOI finds the full text in most of the affected articles, but maybe extending the list at https://github.com/Impactstory/oadoi/blob/bd0391563ff6d767a2cb69e5020e1563df370d72/oa_local.py#L54 would be reasonable as well.

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/dc7d6932fc6abcc5738b85e594750159b66183abc27f5e703cd0c9507e482f54
