### ISSUE TITLE
alternative DOI resolver?

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#51]
Hello,

from twitter I understand that Impact Story has retired the name oaDOI. Question: What will happen to the alternative DOI resolver, i.e. https://oadoi.org/10.3952/lithjphys.48405 resolving to the "best_oa_location"?

Will this service be continued via the oadoi domain?

Another question: Where has the API documentation been moved to?

Thanks & greetings,
inga

**Comment by jasonpriem** [comment]
Thanks for getting in touch! 

The shortcut link will continue to work, using the same URL. It's been baked into a lot of library link resolvers at this point, and so we'll keep supporting it for a while. We recommend the REST API, though...it's almost as easy, and a lot clearer as to what's going on.

A note: we are now calling the "alternative DOI resolver" the "shortcut link," as you may have noticed above. This is in response to some good feedback from Crossref's @gbilder, who pointed out that calling it a "resolver" implies a lot of promises we don't want to make about persistance, robustness, and so on. We don't want to be in that business, as Crossref is already doing a fantastic job.

The API docs are now here: http://unpaywall.org/api/v2
