### ISSUE TITLE
Internal server error when queried with unknown DOI

### ISSUE THREAD

**Issue by stefan-kolb** [Impactstory/oadoi#52]
When I execute the following request an internal server error 500 occurs:
```
https://api.oadoi.org/v2/10.1186/unknown-doi?email=developers@jabref.org
```
Instead I would expect an empty response or a status code of 404 not found.

**Comment by hpiwowar** [comment]
Good catch!  Added the bug yesterday, but now fixed :)  Thanks!
Heather
