### ISSUE TITLE
question: how to appear as open-access in oadoi?

### ISSUE THREAD

**Issue by monperrus** [Impactstory/oadoi#53]
I see that 28 of my own papers don't appear as open-access in oadoi, while they are indeed open-access.

How to identify the problem? how to appear as open-access in oadoi?

**Comment by jasonpriem** [comment]
Sorry to hear about that! Thanks for reporting the bug. If you can let us know the DOIs of the missing papers, we will get to work on fixing it.

**Comment by monperrus** [comment]
Beyond fixing a particular paper, it would be great to understand how to register a paper in oadoi.

What repository is the most appropriate? What metadata is essential? How often is the repo crawled?
What's the duration between a change in an open-access repo and the update in oadoi?

**Comment by hpiwowar** [comment]
Hi!  Thanks for the questions.  Some of them are answered here: http://unpaywall.org/faq
We gather open access from sources listed here: http://unpaywall.org/sources
We harvest daily.  The only metadata that is required from the repository is title and link :)  We harvest via the OA-PMH standard.
Hope that helps!  Are your 28 papers in a repository?  Is it one of the repositories on our sources page?  If not, you can contact your repository librarian and ask her/him to fill out the form to be added and we'll get to work on it :)

**Comment by monperrus** [comment]
Thanks for the information.

Here are the OAI links (on hal.archives-ouvertes.fr) to the papers that are not considered as OA in oadoi.

What is the root cause of the problem?

On 3/26/18 3:26 PM, Heather Piwowar wrote:
```
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01117376
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01279620
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01172102
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01206501
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01321615
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01054552
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01406422
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01387556
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01120913
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01354090
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01078532
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-00697421
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01105173
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01279233
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01575346
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01575966
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01463689
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01063789
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01285008
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01089268
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01182103
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-00903808
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01350515
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01309004
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01419861
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-00517466
  https://api.archives-ouvertes.fr/oai/hal/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hal-01346046
```

**Comment by nemobis** [comment]
(Just checking random issues here.) This report is still current, e.g. https://oadoi.org/10.1007/s10664-013-9282-8 doesn't redirect to any OA version (while https://dissem.in/10.1007/s10664-013-9282-8 knows about PDFs on HAL, arXiv and CiteSeerX).

**Comment by jasonpriem** [comment]
Thanks for the update!

**Comment by monperrus** [comment]
Result of today's check: out of 58 open-access papers on HAL with doi

* 36 are well referenced on oadoi
* 22 still point to the publisher version

How to further debug the problem?

**Comment by jasonpriem** [comment]
Thanks for the update

**Comment by monperrus** [comment]
closing this one. The more qualified question is #62
