### ISSUE TITLE
Fail to detect bronze OA for The Auk papers

### ISSUE THREAD

**Issue by Bisaloo** [Impactstory/oadoi#54]
http://www.bioone.org/doi/abs/10.1642/AUK-18-8.1

Other BioOne journals seem fine. See for example:

- http://www.bioone.org/doi/abs/10.1650/CONDOR-16-62.1
- http://www.bioone.org/doi/abs/10.1080/02724630903413032

From what I understand, there is not much you can do. The journal has to communicate the license to CrossRef in a standard format. Is that right?

**Comment by hpiwowar** [comment]
Hi!  Thanks for the bug report!

We do actually look at the publisher pages as well sometimes, so we might
be able to get these.  Will look into it.  Thanks :)


--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by Bisaloo** [comment]
I'm actually having the same issue for some other BioOne papers:

http://www.bioone.org/doi/abs/10.1650/CONDOR-17-187.1

**Comment by Bisaloo** [comment]
It also does seem to work properly for some "The Auk" papers: 

http://www.bioone.org/doi/abs/10.1642/0004-8038(2005)122%5B0872:WMAFBO%5D2.0.CO%3B2
