### ISSUE TITLE
False positive for Behavioral Ecology journal

### ISSUE THREAD

**Issue by Bisaloo** [Impactstory/oadoi#55]
https://api.oadoi.org/v2/10.1093/beheco/ary021

Paper is actually paywalled on publisher website.

https://academic.oup.com/beheco/advance-article-abstract/doi/10.1093/beheco/ary021/4961327

**Comment by hpiwowar** [comment]
Thanks for letting us know!  We'll get it fixed.
Best,
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>
