### ISSUE TITLE
ACS: half of OA articles not detected by unpaywall

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#58]
Hi,

today I run a couple of OA article from ACS (author choice as well as editor choice) against unpaywall's "Simple Query Tool" and found that the CrossRef license is only found for half of them, see: [acs-unpaywall-result.txt](https://github.com/Impactstory/oadoi/files/1972291/acs-unpaywall-result.txt) (colums A-C = manual lookups, columns D-S = from unpaywall's result)

Greetings
inga

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/4983a48b2bfdc2de6c5bf19724e45d0d4aa3407cf97f13e41ea039686bc88c91

**Comment by nemobis** [comment]
I've searched <https://duckduckgo.com/?q=%22(CC-BY-NC-ND)+Attribution+License%22+site%3Apubs.acs.org&t=ffab&ia=web> and out of 180 DOIS whose PDF contains a CC-BY-NC-ND license there are 16 which Unpaywall considers closed:

10.1021/acsaem.9b01333
10.1021/acs.analchem.8b01208
10.1021/acsapm.9b00503
10.1021/acscatal.9b01748
10.1021/acscatal.9b02213
10.1021/acsenergylett.9b00733
10.1021/acs.estlett.9b00379
10.1021/acsinfecdis.9b00179
10.1021/acs.jpcc.9b01234
10.1021/acs.macromol.9b00359
10.1021/acsmedchemlett.9b00276
10.1021/acssuschemeng.9b01497
10.1021/apv001i008_1302994
10.1021/jacs.9b06246
10.1021/jacs.9b06975
10.1021/jpv123i030_1300553

[acs.dois.notoa.txt](https://github.com/Impactstory/oadoi/files/3755509/acs.dois.notoa.txt)
[acs.dois.oa.txt](https://github.com/Impactstory/oadoi/files/3755510/acs.dois.oa.txt)
[acs.dois.txt](https://github.com/Impactstory/oadoi/files/3755511/acs.dois.txt)
