### ISSUE TITLE
Add 1465k JSTOR works from Internet Archive

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#59]
On https://archive.org/details/journals , almost 1.5 million works are available. The `<id>` in the metadata is supposed to be JSTOR's DOI, although for example here it doesn't resolve: https://archive.org/details/jstor-4559053

With a search on CrossRef you might be able to find the same work with other DOIs, for instance this is the same work: https://api.oadoi.org/v2/10.1001/jama.1907.02520320064008 (no PDF URL provided).

An API library for Internet Archive exists: https://pypi.org/project/internetarchive/

**Comment by jasonpriem** [comment]
Thanks for the suggestion! We are currently working with Internet Archive to share our respective collections with one another more effectively...hopefully will have some announcements on that front in the next few months.
