### ISSUE TITLE
Missing free_fulltext_urls from arxiv

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#6]
Hi, 

thanks a lot for building & sharing oadoi - it is my #favoriteservice of this #oaweek by far! :tada: 

Today I took a small sample from arxiv (set=cs, from=2014-01-01, until=2014-12-31), selected all records with a DOI and checked these DOIs against the oadoi API.

Result: is_free_to_read is False for 369 of the tested DOIs, see: [arxiv2oadoi_cs_2014.txt](https://github.com/Impactstory/oadoi/files/554396/arxiv2oadoi_cs_2014.txt)

Do you want more? 

In addition I have some questions regarding which free_fulltext_url is chosen when several free versions have been found. The development paper mentions that the "choice algorithm" will be documented somewhere... Any hint?

And last but not least: We consider to included oadoi into the institutional link resolver of Max Planck. Do you have any concerns or objections?

Thanks so much & kind regards,
inga

**Comment by hpiwowar** [comment]
This QA is fantastic!!  Thanks so much :)

As you've discovered, we have a known bug:  we fail to find preprints when the preprint title is different than the title of the DOI article.  The good news is that the arXiv record often includes the DOI in the arXiv metadata, and provides a way to query by DOI, so we can find arXiv papers that way even when they have different titles.  This is on our list of things to do, hopefully soon.  

After we implement that we'll revisit your QA results and see how we're doing, and take you up on your offer for more QA, that'd be awesome :)

Good q about the algorithm for how we decide which url to return.  We'll be updating our documentation soon to reflect this.  Short answer:

1.  DOI version if journal is in DOAJ, if is a datacite DOI, or we detect it is free on the publisher's site via our web scraping
2. a link to an IR PDF or IR landing page if we can find one by searching base-search.net by title.  We give preference to ones that base-search.net knows are OA papers (don't have easy way to point you to which these are at the moment, we can get back to you)
3. if there is more than one of those urls, we sort them using the [code here](https://github.com/Impactstory/oadoi/blob/master/oa_base.py#L10).  Will summarize this in the documentation, and point you to that when it's up.

Finally, yes please do use it as an IR link resolver at Max Planck, that'd be awesome!  :)  include ?email=YOUREMAIL in the url so we can contact you in case there are problems and track usage to report to our funders.  That's exciting!  :)

**Comment by ioverka** [comment]
Thank a lot for your swift & helpful response, again!

The Max Planck link resolver started to use oadoi yesterday (I couldn't resist ;) and now adds the email param to all API requests. I will share the code of this implementation with the correspondig community later today and post a link.

... and please: just give me shout out whenever oadoi is ready for some more QA or if there is something else - I'm happy to help!

**Comment by nemobis** [comment]
Another example: https://arxiv.org/abs/1406.0488 (also in https://www.base-search.net/Record/fbcb66347cda99ec8155c2147ce796b310baef0d320828b17ee5c0ae5875f6ac/ ) but http://api.oadoi.org/10.1088/0004-637X/789/2/119 says it's closed.

I guess "$M_\odot$ " or "M⊙" is the culprit here. Looking up the DOI is the way to go, but maybe also making sure that you're comparing titles in Unicode version and not latex or whatever.

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/5d560cdf70dac8c2f1fd6db6d31a8807efb59aba142bc8399a7dc211ea8372f0
