### ISSUE TITLE
How is the "version" detected?

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#60]
Dear team at ImpactStory,

if I understood correctly, some third parties (like Clarivate's Web of Science) use the "version" information to limit the scope of re-use to specific full text types, e.g. peer-reviewed versions (see http://info.clarivate.com/openaccess). So, the obvious folllow-up question is: What measures are used to identify the version? In particular: Can the usage of cover sheets have an impact on the detection?

Sorry if the question has been raised and answered before... I checked some sources including the libraries user guide (http://unpaywall.org/user-guides/libraries - neat idea!) but failed to find the answer myself.

Summer greetings from Munich
inga

**Comment by hpiwowar** [comment]
Nope, cover sheets don't change the detection :)

**Comment by hpiwowar** [comment]
Sorry, hit enter before adding a few more details:  we look for things like copyright indications, page numbers, etc.  We know there is often a cover page... that's fine, our system is built to be robust against that.  Hope that helps!
