### ISSUE TITLE
duplicate sources in  in sources.csv

### ISSUE THREAD

**Issue by monperrus** [Impactstory/oadoi#61]
I notice that there are 3 times `https://hal.archives-ouvertes.fr/` in the sources.csv file (<https://api.oadoi.org/data/sources.csv>).

Is that normal? Does this result in wasted crawling effort?

**Comment by monperrus** [comment]
ping?

**Comment by hpiwowar** [comment]
we're expanding our team and at that point will do a better job of keeping up with issues here.  sorry for the delay!

**Comment by richard-orr** [comment]
This archive operates several repository endpoints, so while the repo homepage is duplicated it doesn't represent duplicated crawling. Thanks!
