### ISSUE TITLE
False positive at Babel Hathi Trust

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#66]
https://oadoi.org/10.2307/2340071 redirects to https://babel.hathitrust.org/cgi/imgsrv/download/pdf?id=uc1.%24b262922;orient=0;size=100;seq=9;attachment=0 which however gives an ERR_INVALID_RESPONSE (in a normal browser with cookies and JavaScript enabled).

Confirmed by another person as well for this DOI. I've seen other cases recently, possibly with other DOI prefixes too, but I didn't keep notes.

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/fb3b765daf0b4f84a0869f0bc4ae111c1528a8ac643fd45085d2c77378853a4c
