### ISSUE TITLE
False negative for Biodiversity Heritage Library (BHL) and IA

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#67]
https://oadoi.org/10.5962/bhl.title.55091 redirects to https://www.biodiversitylibrary.org/bibliography/55091, which is OA although the PDF download link is not the most visible button on the page and is not semantically marked: `<a class="icon pdf" href="https://www.archive.org/download/cu31924094807652/cu31924094807652.pdf">PDF</a>`.

In the API https://api.unpaywall.org/v2/10.5962/bhl.title.55091 `oa_locations` is empty while it should contain the PDF linked from the splash page, https://www.archive.org/download/cu31924094807652/cu31924094807652.pdf (hosted in https://archive.org/details/biodiversity ).

I'm filing this separately from https://github.com/Impactstory/oadoi/issues/59 because I hope that this one only needs minimal changes to the crawler.

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/877e45f3bdd0b9abdabf4a36e229d9b1358919b1f4c0f11f4c3abe691ec4a55e

**Comment by nemobis** [comment]
This is marked "Won't Fix" there, but I think it's actually fixed now. I see hundreds of links to www.archive.org being returned by Unpaywall to OAbot for English Wikipedia citations.
