### ISSUE TITLE
Wrong evidence for journal "RNA"

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#8]
Hello,

https://api.oadoi.org/publication/doi/10.1261/rna.056226.116 states:
```
      "doi": "10.1261/rna.056226.116", 
      "doi_resolver": "crossref", 
      "evidence": "oa journal (via journal title in doaj)", 
```

According to [CrossRef (http://api.crossref.org/works/10.1261/rna.056226.116)], the article was published in: `"container-title":["RNA"],"` with `"ISSN":["1355-8382","1469-9001"]`, but I cannot find this journal in DOAJ. The full text is currently not available...

**Comment by hpiwowar** [comment]
Good catch!  It was getting mixed up with the alternative title of the journal "Revista Nacional de Administración".  Fixed :)  Thanks a lot for the bug report!
