### ISSUE TITLE
False negative (?) for persee.fr

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#88]
https://doi.org/10.3406/comm.1975.1350 is available from the publisher (?) at https://www.persee.fr/docAsPDF/comm_0588-8018_1975_num_23_1_1350.pdf when clicking from https://www.persee.fr/doc/comm_0588-8018_1975_num_23_1_1350 and passing the NoCaptcha. It also carries a CC-BY-NC-ND icon.

API:
```
{
  "best_oa_location": null,
  "data_standard": 2,
  "doi": "10.3406/comm.1975.1350",
  "doi_url": "https://doi.org/10.3406/comm.1975.1350",
  "genre": "journal-article",
  "is_oa": false,
  "journal_is_in_doaj": false,
  "journal_is_oa": false,
  "journal_issns": "0588-8018",
  "journal_name": "Communications",
  "oa_locations": [],
  "published_date": "1975-01-01",
  "publisher": "PERSEE Program",
  "title": "Souvenir-\u00e9cran",
  "updated": "2018-06-20T21:15:13.613453",
  "year": 1975,
  "z_authors": [
    {
      "family": "Rosolato",
      "given": "Guy"
    }
  ]
}
```

**Comment by richard-orr** [comment]
https://support.unpaywall.org/public/tickets/0393c7d168793d1e35bcaf906e96f5256319c701112e155cdd8cf9a264543363
