### ISSUE TITLE
For book DOIs scraping the publisher landing page can be tricky

### ISSUE THREAD

**Issue by ioverka** [Impactstory/oadoi#9]
Hello again,

sorry for bothering you with another issue. https://api.oadoi.org/publication/doi/10.1002/9781118636817 states:

```
      "doi": "10.1002/9781118636817", 
      "doi_resolver": "crossref", 
      "evidence": "publisher landing page", 
      "free_fulltext_url": "http://onlinelibrary.wiley.com/doi/10.1002/9781118636817.fmatter/pdf", 
```

On the corresponding landing page, you will notice that only the front matter and the index are "free_to_read". I guess this might be the case for quite a lot of subscription ebooks.

Greetings from Munich,
inga

**Comment by hpiwowar** [comment]
thanks for reporting this!

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/ff1930f4cb740870e233e7fa9c14a86b3d3182d27b5bc43d264b926b6f794d46
